codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  precision: 5
  range:
    - 60.0
    - 80.0
  round: up
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project:
      default:
        base: auto
        branches:
          - ^master$
        flags:
          - abi
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
        paths:
          - ^src.*
fixes:
  - '/home/runner/work/web3j/web3j/::'
github_checks:
  annotations: true